### ISSUE TITLE
看了你的博客，求教下博客搭建。

### ISSUE THREAD

**Issue by Palenew** [qinshenxue/vue2-vue-router2-webpack2#2]
在你的博客上留言了，但是似乎你没注意，跑来github问，请教下博客搭建有什么经验可以分享吗？
我也想做个博客，想要自己买服务器搭建，不知道你的博客是自己的服务器搭建的吗？还是用的别的什么东西搭起来的，可以分享一下吗。

感谢！

**Comment by qinshenxue** [comment]
博客是 阿里云的服务器，
